version: '3.2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.8.2
    volumes:
      - source: ./logstash/gelf.conf
        target: /usr/share/logstash/pipeline/gelf.conf
        type: bind
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
